# actionlint configuration file
# See: https://github.com/rhysd/actionlint/blob/main/docs/config.md

# Shellcheck configuration
shellcheck:
  # Don't ignore any shellcheck warnings
  ignore: []
  # Include all shellcheck checks
  include: []
  # Set shellcheck severity level to error to catch all issues
  severity: "error"
  # Use bash as the default shell
  shell: "bash"
  # Additional shellcheck options
  options:
    - "-x" # Follow source statements
    - "-a" # Consider all files to be bash scripts
    - "-o" # Enable all optional checks
    - "all"

# Don't ignore any actionlint warnings
ignore: []

# Self-hosted runner labels
self-hosted-runner:
  labels:
    - "ubuntu-latest"
    - "windows-latest"
    - "macos-latest"
