version: 2
updates:
  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    reviewers:
      - "rice.adam"
    assignees:
      - "rice.adam"
    commit-message:
      prefix: "deps"
      include: "scope"
    ignore:
      - dependency-name: "uv"
        versions: ["0.6.14"]
      - dependency-name: "hatch"
        versions: ["1.9.0"]
      - dependency-name: "python-semantic-release"
        versions: ["9.0.0"]
    groups:
      dev-dependencies:
        patterns:
          - "ruff"
          - "pyright"
          - "pre-commit"
          - "build"
          - "hatch"
          - "types-*"
      test-dependencies:
        patterns:
          - "pytest*"
          - "coverage"
      docs-dependencies:
        patterns:
          - "mkdocs*"
          - "pymdown*"
