name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'dependencies'
  - title: '📚 Documentation'
    labels:
      - 'documentation'
      - 'docs'
  - title: '⚡ Performance'
    labels:
      - 'performance'
      - 'perf'
  - title: '🔧 Refactoring'
    labels:
      - 'refactor'
  - title: '🧪 Testing'
    labels:
      - 'test'
      - 'testing'
  - title: '🏗️ Build'
    labels:
      - 'build'
      - 'ci'
  - title: '🎨 Style'
    labels:
      - 'style'
  - title: '⏪ Reverts'
    labels:
      - 'revert'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## What's Changed

  $CHANGES

  ## Installation

  ```bash
  pip install conda-forge-converter==$RESOLVED_VERSION
  ```

  ## Documentation

  For more information, see the [documentation](https://github.com/$GITHUB_REPOSITORY#readme).

  ## Contributors

  $CONTRIBUTORS

  ## Security

  If you discover any security related issues, please email security@example.com instead of using the issue tracker.

  ## License

  The MIT License (MIT). Please see [License File](LICENSE) for more information.
