# GitHub Actions Workflow Configuration
# This file centralizes configuration for all workflows

# Python settings
python:
  versions:
    - "3.11"
    - "3.12"
  default: "3.11"
  extras:
    dev: true
    test: true
    docs: false
  uv:
    version: "0.7.1"
    enabled: true

# Testing settings
testing:
  parallel: true
  timeout: 10m
  coverage:
    enabled: true
    threshold: 80
    fail_under: 70
  markers:
    critical: "Tests that must pass before running other tests"
    integration: "Integration tests that may take longer to run"
    slow: "Tests that take a long time to run"

# Linting settings
linting:
  tools:
    - ruff
  type_checking: true
  format_checking: true
  auto_fix: false
  fail_on_error: true

# Security settings
security:
  enabled: true
  tools:
    - bandit
    - safety
  fail_on_error: false

# Local testing settings
local_testing:
  simplified_matrix: true
  skip_steps:
    - "Upload coverage to Codecov"
    - "Run security checks"
  environment_variables:
    ACT_LOCAL_TESTING: "true"
    SKIP_DOCKER_BUILDS: "true"
    SKIP_LONG_RUNNING_TESTS: "true"

# Workflow settings
workflows:
  ci:
    branches:
      - main
      - develop
    progressive_testing: true
    debug_mode_available: true

  release:
    approval_required: true
    version_bump_types:
      - patch
      - minor
      - major
    auto_release_notes: true

  docs:
    auto_deploy: true
    preview_prs: true
