# Title for the gitleaks configuration file
title = "Gitleaks Configuration"

# Extend from the default gitleaks config
[extend]
useDefault = true

# Define custom rules
[[rules]]
id = "generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|apikey|secret|token)[_-]?[[:alnum:]]{16,}'''
secretGroup = 1
entropy = 3.5

[[rules]]
id = "generic-secret"
description = "Generic Secret"
regex = '''(?i)secret[_-]?[[:alnum:]]{16,}'''
secretGroup = 1
entropy = 3.5

# Define paths and patterns to allow
[allowlist]
description = "Allowed patterns and paths"
paths = [
    '''(?i).*\.test\..*''',
    '''(?i).*test[s]?/.*''',
    '''(?i).*mock[s]?/.*''',
    '''(?i).*example[s]?/.*''',
    '''(?i).*fixture[s]?/.*''',
    '''\.coverage/.*''',
    '''\.coverage$''',
    '''\.pytest_cache/.*''',
    '''\.ruff_cache/.*''',
    '''\.mypy_cache/.*''',
    '''\.hypothesis/.*''',
    '''\.tox/.*''',
    '''\.venv/.*''',
    '''\.env/.*''',
    '''\.uv/.*''',
    '''uv\.lock$''',
    '''requirements/.*\.txt$''',
    '''poetry\.lock$''',
    '''Pipfile\.lock$''',
    '''\.git/.*''',
    '''\.github/.*''',
    '''\.gitlab/.*''',
    '''\.vscode/.*''',
    '''\.idea/.*''',
    '''pyproject\.toml$''',
]

# Allow specific files and lines that trigger false positives
[[allowlist.files]]
path = '''src/conda_forge_converter/utils.py'''
line_number = 46
regexes = [
    '''(?i)example[_-]?key''',
    '''(?i)test[_-]?key''',
    '''(?i)dummy[_-]?key''',
    '''github-actions\[bot\]@users\.noreply\.github\.com''',
    '''actions@github\.com''',
    '''user_module = None''',                                # Allow Unix module import fallback
]

[[rules]]
id = "github-pat"
description = "GitHub Personal Access Token"
regex = '''(?i)(ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9_]{36}'''

[[rules]]
id = "aws-access-key-id"
description = "AWS Access Key ID"
regex = '''(A3T[A-Z0-9]|AKIA|AGPA|AIDA|APOA|AIPA|ANPA|ANVA|ASIA)[A-Z0-9]{16}'''

[[rules]]
id = "aws-secret-access-key"
description = "AWS Secret Access Key"
regex = '''(?i)aws[_-]?(?:secret[_-]?)?key[_-]?(?:id)?['\"]?\s*[:=]\s*['"]?[A-Za-z0-9/+=]{40}['"]?'''

[[rules]]
id = "private-key"
description = "Private Key"
regex = '''(?i)-----BEGIN (?:RSA|DSA|EC|PGP|OPENSSH) PRIVATE KEY-----'''

[[rules]]
id = "password"
description = "Password"
regex = '''(?i)(password|passwd|pwd)['\"]?\s*[:=]\s*['"]?[^'"]+['"]?'''

[[rules]]
id = "email"
description = "Email"
regex = '''[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}'''

[[rules]]
id = "ip-address"
description = "IP Address"
regex = '''\b(?:\d{1,3}\.){3}\d{1,3}\b'''
