# Markdownlint configuration for documentation quality
default: true

# MD013 - Line length
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# MD024 - Multiple headers with the same content
MD024:
  siblings_only: true

# MD033 - Inline HTML
MD033: false

# MD041 - First line in a file should be a top-level header
MD041: false

# MD046 - Code block style
MD046:
  style: fenced

# MD007 - Unordered list indentation
MD007:
  indent: 2

# MD029 - Ordered list item prefix
MD029:
  style: ordered

# MD004 - Unordered list style
MD004:
  style: dash
