name: "Setup Python Environment"
description: "Sets up Python with UV and installs dependencies"
inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.11"
  install-extras:
    description: 'Extras to install (comma-separated, e.g., "dev,test")'
    required: false
    default: "dev,test"
  cache-key:
    description: "Custom cache key for dependencies"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"

    - name: Install UV
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          ~/.cache/pip
        key: ${{ runner.os }}-py${{ inputs.python-version }}-uv-${{ inputs.cache-key || hashFiles('requirements.lock') }}
        restore-keys: |
          ${{ runner.os }}-py${{ inputs.python-version }}-uv-

    - name: Install dependencies
      shell: bash
      run: |
        # Parse extras
        EXTRAS=""
        IFS=',' read -ra ADDR <<< "${{ inputs.install-extras }}"
        for i in "${ADDR[@]}"; do
          EXTRAS="$EXTRAS,$i"
        done

        if [ -n "$EXTRAS" ]; then
          EXTRAS="${EXTRAS:1}"  # Remove leading comma
          uv pip install -e ".[${EXTRAS}]" --system
        else
          uv pip install -e "." --system
        fi

        # Print installed packages for debugging
        echo "Installed packages:"
        pip list
