blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/orgs/your-org/discussions
    about: Please ask and answer questions here.
  - name: Security Issues
    url: https://github.com/your-org/your-repo/security/policy
    about: Please report security vulnerabilities here.
  - name: Documentation
    url: https://conda-forge-converter.readthedocs.io/
    about: Check the documentation before reporting issues.
