name: "Setup Python Environment"
description: "Sets up Python environment with UV and dependency caching"

inputs:
  python-version:
    description: "Python version to use"
    required: true
    default: "3.11"
  uv-version:
    description: "UV version to use"
    required: true
    default: "0.6.14"
  cache-key:
    description: "Cache key prefix"
    required: true
  extra-cache-paths:
    description: "Additional paths to cache"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: "pip"

    - name: Install UV
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install uv==${{ inputs.uv-version }}
        uv --version

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/uv
          ~/.cache/pip
          ${{ inputs.extra-cache-paths }}
        key: ${{ inputs.cache-key }}-${{ runner.os }}-py${{ inputs.python-version }}-uv${{ inputs.uv-version }}-${{ hashFiles('requirements.lock') }}
        restore-keys: |
          ${{ inputs.cache-key }}-${{ runner.os }}-py${{ inputs.python-version }}-uv${{ inputs.uv-version }}-
