name: Branch Protection

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - master

# Prevent concurrent runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: '3.11'
  CACHE_KEY: ubuntu-pip-v1

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/uv
          key: ${{ env.CACHE_KEY }}
          restore-keys: |
            ${{ env.CACHE_KEY }}

      - name: Install dependencies
        run: |
          uv pip install hatch --system  # Only needed for version management
          hatch env create # TODO: replace with uv venv for speed
          # Explicitly install test and linting dependencies
          hatch env run -- pip install pytest pytest-cov ruff pyright

      - name: Check version format
        run: |
          VERSION=$(hatch version)
          if ! [[ $VERSION =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Invalid version format: $VERSION"
            exit 1
          fi

      - name: Check CHANGELOG.md
        if: github.event_name == 'pull_request'
        run: |
          if ! git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} | grep -q "CHANGELOG.md"; then
            echo "Error: CHANGELOG.md must be updated with version changes"
            exit 1
          fi

      - name: Run linting
        run: |
          hatch run lint
          hatch run type-check

      - name: Run tests
        run: |
          if [ "$ACT_LOCAL_TESTING" = "true" ]; then
            # In local testing mode, run tests but don't fail the workflow if they fail
            hatch run pytest --cov=conda_forge_converter --cov-report=term-missing --cov-report=xml --junitxml=pytest.xml tests/ || echo "Tests failed but continuing for local testing"
            exit 0
          else
            # In normal mode, run tests and fail if they fail
            hatch run pytest --cov=conda_forge_converter --cov-report=term-missing --cov-report=xml --junitxml=pytest.xml tests/
          fi

      - name: Check commit message format
        if: github.event_name == 'pull_request'
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if ! [[ $COMMIT_MSG =~ ^(feat|fix|docs|style|refactor|test|chore|perf|ci|build|revert)(\([a-z0-9-]+\))?: .+ ]]; then
            echo "Error: Invalid commit message format. Must follow Conventional Commits specification."
            echo "Example: feat(api): add new endpoint"
            exit 1
          fi

      - name: Check PR size
        if: github.event_name == 'pull_request' && env.ACT_LOCAL_TESTING != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const response = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            const additions = response.data.additions;
            const deletions = response.data.deletions;
            const changedFiles = response.data.changed_files;

            console.log(`PR Stats: ${additions} additions, ${deletions} deletions, ${changedFiles} files changed`);

            // Define thresholds
            const LARGE_THRESHOLD = 500;
            const VERY_LARGE_THRESHOLD = 1000;

            if (additions + deletions > VERY_LARGE_THRESHOLD) {
              core.warning(`⚠️ This PR is very large (${additions} additions, ${deletions} deletions). Consider breaking it into smaller PRs.`);
            } else if (additions + deletions > LARGE_THRESHOLD) {
              core.notice(`ℹ️ This PR is large (${additions} additions, ${deletions} deletions). Consider if it could be broken down further.`);
            }

            // Don't fail the build, just warn

      - name: Mock PR size check for local testing
        if: github.event_name == 'pull_request' && env.ACT_LOCAL_TESTING == 'true'
        run: |
          echo "Running in local testing mode - skipping actual PR size check"
          echo "This is a mock step to ensure the workflow completes successfully in local testing"

      - name: Upload test results
        if: always() && env.ACT_LOCAL_TESTING != 'true'
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            .coverage
            coverage.xml
            pytest.xml
          retention-days: 30

      - name: Mock upload test results for local testing
        if: always() && env.ACT_LOCAL_TESTING == 'true'
        run: |
          echo "Running in local testing mode - skipping actual test results upload"
          echo "This is a mock step to ensure the workflow completes successfully in local testing"

  verify-protection:
    name: Verify Branch Protection
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify branch protection settings
        if: env.ACT_LOCAL_TESTING != 'true'
        uses: actions/github-script@v7
        with:
          script: |
            try {
              // Get the branch protection settings
              const branch = github.ref.replace('refs/heads/', '');
              console.log(`Checking branch protection for ${branch}`);

              const { data: protection } = await github.rest.repos.getBranchProtection({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: branch
              });

              // Check required status checks
              if (!protection.required_status_checks) {
                core.warning(`⚠️ Branch ${branch} does not have required status checks enabled.`);
              }

              // Check required PR reviews
              if (!protection.required_pull_request_reviews) {
                core.warning(`⚠️ Branch ${branch} does not have required pull request reviews enabled.`);
              } else {
                const requiredReviewers = protection.required_pull_request_reviews.required_approving_review_count || 0;
                if (requiredReviewers < 1) {
                  core.warning(`⚠️ Branch ${branch} requires ${requiredReviewers} reviewers. Consider requiring at least 1 reviewer.`);
                }
              }

              // Check admin enforcement
              if (!protection.enforce_admins.enabled) {
                core.warning(`⚠️ Branch ${branch} does not enforce protections for administrators.`);
              }

              console.log('Branch protection verification completed.');
            } catch (error) {
              core.warning(`⚠️ Could not verify branch protection settings: ${error.message}`);
              core.warning('Please ensure branch protection is enabled in repository settings:');
              core.warning('Settings > Branches > Branch protection rules > Add rule');
              core.warning('Recommended settings:');
              core.warning('- Require pull request reviews before merging');
              core.warning('- Require status checks to pass before merging');
              core.warning('- Require branches to be up to date before merging');
              core.warning('- Include administrators');
            }
            
      - name: Mock branch protection verification for local testing
        if: env.ACT_LOCAL_TESTING == 'true'
        run: |
          echo "Running in local testing mode - skipping actual branch protection verification"
          echo "This is a mock step to ensure the workflow completes successfully in local testing"
