name: CI

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

permissions:
  contents: read
  pull-requests: write
  checks: write
  issues: write

env:
  # Load default values from variables file
  PYTHON_VERSION: ${{ vars.PYTHON_VERSION || '3.11' }}
  UV_VERSION: ${{ vars.UV_VERSION || '0.6.14' }}
  ACT_LOCAL_TESTING: ${{ vars.ACT_LOCAL_TESTING || 'false' }}
  COVERAGE_THRESHOLD: ${{ vars.COVERAGE_THRESHOLD || '60' }}

jobs:
  test:
    name: Test (${{ matrix.os }}, Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    timeout-minutes: ${{ vars.TEST_TIMEOUT_MINUTES && fromJSON(vars.TEST_TIMEOUT_MINUTES) || 30 }}
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]
      fail-fast: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-python
        with:
          python-version: ${{ matrix.python-version }}
          uv-version: ${{ env.UV_VERSION }}
          cache-key: test
          extra-cache-paths: |
            ~/.cache/hatch
            .coverage
            coverage.xml

      - name: Install dependencies
        run: |
          uv pip install -e ".[dev,test]" --system --no-deps
          uv pip install -r requirements.lock

      - name: Run linting and type checking
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.11'
        run: |
          hatch run lint
          hatch run type-check

      - name: Run tests
        run: |
          hatch run test

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results-${{ matrix.os }}-py${{ matrix.python-version }}
          path: |
            .coverage
            coverage.xml
          retention-days: 30

      - name: Upload coverage to Codecov
        uses: ./.github/actions/mock-service
        with:
          service-name: Codecov
          mock-script: |
            echo "Coverage report available at coverage.xml"
            echo "In production, this would upload to Codecov"
