name: Documentation

on:
  push:
    branches: [ master, develop ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - 'mkdocs.yml'
  pull_request:
    branches: [ master, develop ]
    paths:
      - 'docs/**'
      - '.github/workflows/docs.yml'
      - 'mkdocs.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  pull-requests: write  # Needed for commenting on PRs
env:
  ACT_LOCAL_TESTING: ${{ vars.ACT_LOCAL_TESTING || 'false' }}
  PYTHON_VERSION: "3.11"
  UV_VERSION: "0.7.1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Install UV
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            ~/.cache/pip
          key: ${{ runner.os }}-py${{ env.PYTHON_VERSION }}-uv${{ env.UV_VERSION }}-docs-${{ hashFiles('requirements.lock') }}
          restore-keys: |
            ${{ runner.os }}-py${{ env.PYTHON_VERSION }}-uv${{ env.UV_VERSION }}-docs-

      - name: Install dependencies
        run: |
          # Install the project with docs extras to get all documentation dependencies
          uv pip install -e ".[docs]" --system

      - name: Check spelling
        run: |
          uv pip install codespell --system
          codespell --skip="*.pyc,*.git,*.png,*.jpg,*.jpeg,*.gif,*.svg,*.ico" --quiet-level=2 docs/

      - name: Build MkDocs site
        run: |
          hatch run docs-build -- --strict

      # This step is skipped in local testing mode
      - name: Upload artifact (Production)
        uses: actions/upload-pages-artifact@v3
        if: ${{ !env.ACT_LOCAL_TESTING || env.ACT_LOCAL_TESTING != 'true' }}
        with:
          path: ./site

      # This step only runs in local testing mode
      - name: Mock artifact upload (Local Testing)
        if: ${{ env.ACT_LOCAL_TESTING == 'true' }}
        run: |
          echo "Mocking artifact upload for local testing"
          echo "Documentation built successfully to ./site directory"
          ls -la ./site

      - name: Check for broken links
        run: |
          uv pip install linkchecker --system
          linkchecker --check-extern ./site/index.html || true  # Don't fail the build if links are broken, just report them

  deploy:
    name: Deploy Documentation
    needs: build
    if: github.ref == 'refs/heads/master' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      # This step is skipped in local testing mode
      - name: Deploy to GitHub Pages (Production)
        id: deployment
        uses: actions/deploy-pages@v4
        if: ${{ !env.ACT_LOCAL_TESTING || env.ACT_LOCAL_TESTING != 'true' }}

      # This step only runs in local testing mode
      - name: Mock GitHub Pages deployment (Local Testing)
        if: ${{ env.ACT_LOCAL_TESTING == 'true' }}
        run: |
          echo "Mocking GitHub Pages deployment for local testing"
          echo "In production, this would deploy the site to GitHub Pages"
          echo "Documentation is available locally in the ./site directory"
