name: Documentation Quality

on:
  pull_request:
    paths:
      - 'docs/**'
      - '**/*.md'
      - 'mkdocs.yml'
      - '.pymarkdown.json'
      - '.github/workflows/docs-quality.yml'
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - '**/*.md'
      - 'mkdocs.yml'
      - '.pymarkdown.json'
      - '.github/workflows/docs-quality.yml'

jobs:
  pymarkdown-lint:
    name: PyMarkdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install PyMarkdown
        run: pip install pymarkdown

      - name: Run PyMarkdown
        run: pymarkdown scan --config .pymarkdown.json .

  mkdocs-build:
    name: MkDocs Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install MkDocs and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material pymdown-extensions

      - name: Build MkDocs site
        run: mkdocs build --strict

  spelling-check:
    name: Spelling Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install codespell
        run: pip install codespell

      - name: Check spelling
        run: codespell --skip="*.pyc,*.git,*.png,*.jpg,*.jpeg,*.gif,*.svg,*.ico" --quiet-level=2
