name: Initialize gh-pages Branch

on:
  workflow_dispatch:
    inputs:
      confirm:
        description: 'Type "yes" to confirm initialization of gh-pages branch'
        required: true
        default: 'no'

jobs:
  initialize:
    name: Initialize gh-pages Branch
    runs-on: ubuntu-latest
    if: github.event.inputs.confirm == 'yes'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for branch creation

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Initialize gh-pages branch
        run: |
          bash .github/scripts/initialize-gh-pages.sh
