name: Validate Workflows

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    branches: [master, develop]
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

env:
  ACT_LOCAL_TESTING: ${{ vars.ACT_LOCAL_TESTING || 'false' }}

jobs:
  validate:
    name: Validate GitHub Actions Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # This step is skipped in local testing mode
      - name: Run actionlint (Production)
        if: ${{ !env.ACT_LOCAL_TESTING || env.ACT_LOCAL_TESTING != 'true' }}
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true

      # This step only runs in local testing mode
      - name: Mock actionlint (Local Testing)
        if: ${{ env.ACT_LOCAL_TESTING == 'true' }}
        run: |
          echo "Mocking actionlint for local testing"
          echo "In production, this would validate GitHub Actions workflow files"
          echo "You can run actionlint locally with: actionlint .github/workflows/*.yml"
