name: Validate Workflows

on:
  pull_request:
    paths:
      - '.github/workflows/**'
  push:
    branches: [main, develop]
    paths:
      - '.github/workflows/**'
  workflow_dispatch:

env:
  ACT_LOCAL_TESTING: ${{ vars.ACT_LOCAL_TESTING || 'false' }}

jobs:
  validate:
    name: Validate GitHub Actions Workflows
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run actionlint
        if: env.ACT_LOCAL_TESTING != 'true'
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: true

      - name: Skip actionlint for local testing
        if: env.ACT_LOCAL_TESTING == 'true'
        run: |
          echo "Skipping actionlint in local testing mode"
          echo "This step would normally validate GitHub Actions workflow files"
