name: Version Bump

on:
  push:
    branches:
      - develop
    paths-ignore:
      - 'src/conda_forge_converter/_version.py'
      - 'CHANGELOG.md'

jobs:
  semantic-release:
    name: Bump Development Version
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-semantic-release build

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Semantic Release
        run: |
          semantic-release version --no-commit --no-tag --no-push --no-vcs-release

      - name: Commit changes
        run: |
          git add src/conda_forge_converter/_version.py CHANGELOG.md
          git commit -m "chore: bump development version [skip ci]"
          git push
